version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - run: Write-Host 'Goodbye, Windows. For I am blocked'
      - run: Write-Host 'Hello darkness my old friend'
