version: 2.1

jobs:
  build:
    resource_class: large
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  testing:
    jobs:
      - build
